services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wikijs
      MYSQL_USER: wikijs
      MYSQL_PASSWORD: wikijs_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  wikijs:
    image: ghcr.io/requarks/wiki:2
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=wikijs
      - DB_PASS=wikijs_password
      - DB_NAME=wikijs
    ports:
      - "8888:3000"
    volumes:
      - wikijs-data:/wiki/data

volumes:
  mysql-data:
  wikijs-data: